inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Metrics/ParameterLists:
  Max: 8
