name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'README.md'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install yard
        run: gem install yard
      - name: Generate docs
        run: yard doc
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.5.0
        with:
          branch: gh-pages
          folder: doc
