name: Documentation

on:
  push:
    tags:
      - v*
  workflow_dispatch:
  schedule:
    # Build docs semi-monthly so broken docs generation is caught before a
    # release tries to publish it.
    - cron: "0 3 1,15 * *"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          bundler-cache: true
          ruby-version: ruby
      - name: Generate docs
        run: bundle exec rake rdoc
      - name: Deploy docs
        if: >-
          (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: doc
