name: Tests - LavinMQ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
        include:
          - { ruby: jruby }
          - { ruby: truffleruby }
    steps:
    - name: Install LavinMQ
      uses: cloudamqp/lavinmq-action@v1
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests (excluding TLS tests) (JRuby)
      if: ${{ matrix.ruby == 'jruby' }}
      run: bundle exec rake
      env:
        JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
    - name: Run tests (excluding TLS tests)
      if: ${{ matrix.ruby != 'jruby' }}
      run: bundle exec rake

  tls:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "ruby"
          - "jruby"
          - "truffleruby"
    steps:
    - name: Install LavinMQ
      uses: cloudamqp/lavinmq-action@v1
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run TLS tests (JRuby)
      if: ${{ matrix.ruby == 'jruby' }}
      run: bin/test-tls lavinmq
      env:
        JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
    - name: Run TLS tests
      if: ${{ matrix.ruby != 'jruby' }}
      run: bin/test-tls lavinmq

  macos:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "ruby"
    steps:
    - name: Install LavinMQ
      run: |
        brew update
        brew install lavinmq
    - name: Start LavinMQ
      run: brew services start lavinmq
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests (excluding TLS tests)
      run: bundle exec rake
