name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ruby
    - name: Run RuboCop
      run: bundle exec rake rubocop
