name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: ${{ matrix.ruby }} (${{ matrix.broker }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        broker: [lavinmq, rabbitmq]
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
        include:
          - { ruby: jruby, broker: lavinmq, allow-failure: false }
          - { ruby: truffleruby, broker: lavinmq, allow-failure: false }
    steps:
    - name: Install LavinMQ
      if: matrix.broker == 'lavinmq'
      uses: cloudamqp/lavinmq-action@v1
    - name: Configure dpkg to skip building man pages
      if: matrix.broker == 'rabbitmq'
      run: |
        echo 'path-exclude /usr/share/doc/*' | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
        echo 'path-exclude /usr/share/man/*' | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
    - name: Install RabbitMQ
      if: matrix.broker == 'rabbitmq'
      run: sudo apt-get update && sudo apt-get install -y rabbitmq-server
    - name: Verify RabbitMQ started correctly
      if: matrix.broker == 'rabbitmq'
      run: while true; do sudo rabbitmq-diagnostics status 2>/dev/null && break; echo -n .; sleep 2; done
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests (excluding TLS tests) (JRuby)
      if: ${{ matrix.ruby == 'jruby' }}
      continue-on-error: ${{ matrix.allow-failure || false }}
      run: bundle exec rake
      env:
        JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
    - name: Run tests (excluding TLS tests)
      if: ${{ matrix.ruby != 'jruby' }}
      continue-on-error: ${{ matrix.allow-failure || false }}
      run: bundle exec rake

  tls:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "ruby" # latest stable release
          - "jruby"
          - "truffleruby"
    steps:
    - name: Install LavinMQ
      uses: cloudamqp/lavinmq-action@v1
    - name: Stop LavinMQ
      run: sudo systemctl stop lavinmq
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install github.com/FiloSottile/mkcert
      run: brew install mkcert
    - name: Create local CA
      run: sudo CAROOT=/etc/lavinmq $(brew --prefix)/bin/mkcert -install
    - name: Create certificate
      run: |
        sudo $(brew --prefix)/bin/mkcert -key-file /etc/lavinmq/localhost-key.pem -cert-file /etc/lavinmq/localhost.pem localhost
        sudo chmod +r /etc/lavinmq/localhost-key.pem
    - name: Create LavinMQ config
      run: |
        sudo tee /etc/lavinmq/lavinmq.ini <<'EOF'
        [main]
        data_dir = /var/lib/lavinmq
        tls_cert = /etc/lavinmq/localhost.pem
        tls_key = /etc/lavinmq/localhost-key.pem

        [amqp]
        tls_port = 5671
        EOF
    - name: Start LavinMQ
      run: sudo systemctl start lavinmq
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run TLS tests (JRuby)
      if: ${{ matrix.ruby == 'jruby' }}
      run: bundle exec rake
      env:
        JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
        TEST_AMQP_HOST: "localhost"
        TESTOPTS: --name=/_tls$/
    - name: Run TLS tests
      if: ${{ matrix.ruby != 'jruby' }}
      run: bundle exec rake
      env:
        TESTOPTS: --name=/_tls$/

  rabbitmq-sudo-tests:
    name: RabbitMQ sudo tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Configure dpkg to skip building man pages
      run: |
        echo 'path-exclude /usr/share/doc/*' | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
        echo 'path-exclude /usr/share/man/*' | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
    - name: Install RabbitMQ
      run: sudo apt-get update && sudo apt-get install -y rabbitmq-server
    - name: Verify RabbitMQ started correctly
      run: while true; do sudo rabbitmq-diagnostics status 2>/dev/null && break; echo -n .; sleep 2; done
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ruby
    - name: Run blocked connection tests
      run: bundle exec rake test:rabbitmq

  macos:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby: # enough to test one Ruby on macOS
          - "ruby" # latest stable release
    steps:
    - name: Install LavinMQ
      run: brew install cloudamqp/cloudamqp/lavinmq
    - name: Start LavinMQ
      run: brew services start lavinmq
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests (excluding TLS tests)
      run: bundle exec rake

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ruby
    - name: Run RuboCop
      run: bundle exec rake rubocop
